version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://inventory_user:inventory_pass@db:5432/inventory_db

volumes:
  db_data: